"""empty message

Revision ID: 798756dcba79
Revises: 
Create Date: 2024-06-26 07:36:32.065834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798756dcba79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
